#!bin/bash

gclone() {
    c_pwd=`pwd`
    cd $HOME/Devel
    git clone git@github.com:k0pernicus/$1.git
    cd $c_pwd
}

update_hugo() {
    c_pwd=`pwd`
    cd $HOME/Devel
    [[ -d hugo ]] || git clone https://github.com/gohugoio/hugo.git && \
    cd hugo && \
    git pull && \
    go install --tags extended
    cd $c_pwd
}

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    FLAKE_DIR="$HOME/Devel/dotfiles/config/nixos-config"
    FLAKE_TARGET="$FLAKE_DIR/#phobos"
    REBUILD_CMD="nixos-rebuild"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    FLAKE_DIR="$HOME/System/nix-darwin-config"
    FLAKE_TARGET="$FLAKE_DIR"
    REBUILD_CMD="darwin-rebuild"
fi

if [[ -n "$FLAKE_DIR" ]]; then
    update_system() {
        echo "Updating nix system for target $FLAKE_TARGET..."
        sudo "$REBUILD_CMD" switch --flake "$FLAKE_TARGET"
    }

    update_nix() {
        echo "Updating flake inputs in $FLAKE_DIR..."
        (cd "$FLAKE_DIR" && sudo nix flake update)
    }
fi
