#!bin/bash

gclone() {
    c_pwd=`pwd`
    cd $HOME/Devel
    git clone git@github.com:k0pernicus/$1.git
    cd $c_pwd
}

update_hugo() {
    c_pwd=`pwd`
    cd $HOME/Devel
    [[ -d hugo ]] || git clone https://github.com/gohugoio/hugo.git && \
    cd hugo && \
    git pull && \
    go install --tags extended
    cd $c_pwd
}

install_swiftly() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        curl -L https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz > $HOME/Downloads/swiftly.tar.gz && \
        tar zxf $HOME/Downloads/swiftly.tar.gz && \
        ./$HOME/Downloads/swiftly/swiftly init && \
        rm -r $HOME/Downloads/swiftly.tar.gz $HOME/Downloads/swiftly
    elif [[ "$OSTYPE" == "darwin"* ]]; then
         curl -L https://download.swift.org/swiftly/darwin/swiftly.pkg > $HOME/Downloads/swiftly.pkg && \
        installer -pkg $HOME/Downloads/swiftly.pkg -target CurrentUserHomeDirectory && \
        rm $HOME/Downloads/swiftly.pkg && \
        $HOME/.swiftly/bin/swiftly init
    fi
}

gemini() {
    local current_dir="$(pwd)"

    # Check if the current directory path contains "/Devel/" or ends with "/Devel"
    if [[ "$current_dir" != */Devel/* ]] && [[ "$current_dir" != */Devel ]]; then
        echo "! Run inside a 'Devel' directory to run the gemini-cli sandbox !"
        return 1
    fi

    mkdir -p "$HOME/.gemini-docker-state"
    echo "Directory check passed. Launching gemini-cli sandbox..."

    # Launch the docker container with the current directory mounted to /workspace
    docker run -it --rm \
        --user "$(id -u):$(id -g)" \
        -e HOME=/gemini-home \
        -v "$current_dir:/workspace" \
        -v "$HOME/.gemini-docker-state:/gemini-home" \
        -w /workspace \
        us-docker.pkg.dev/gemini-code-dev/gemini-cli/sandbox:0.36.0
}

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    FLAKE_DIR="$HOME/Devel/dotfiles/system/nixos-config"
    FLAKE_TARGET="$FLAKE_DIR/#phobos"
    REBUILD_CMD="nixos-rebuild"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    FLAKE_DIR="$HOME/System/nix-darwin-config"
    FLAKE_TARGET="$FLAKE_DIR"
    REBUILD_CMD="darwin-rebuild"
fi

if [[ -n "$FLAKE_DIR" ]]; then
    update_system() {
        echo "Updating nix system for target $FLAKE_TARGET..."
        sudo "$REBUILD_CMD" switch --flake "$FLAKE_TARGET"
    }

    update_nix() {
        echo "Updating flake inputs in $FLAKE_DIR..."
        (cd "$FLAKE_DIR" && sudo nix flake update)
    }
fi
