# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-33ea8185-8516-4451-a99a-5fbf02c523ee";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-33ea8185-8516-4451-a99a-5fbf02c523ee".device = "/dev/disk/by-uuid/33ea8185-8516-4451-a99a-5fbf02c523ee";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EF82-AACB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-667c2261-a769-44d9-8310-cdd1e6f421cd"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true; # enable the bluetooth module
  hardware.bluetooth.powerOnBoot = false; # do not power up the bluetooth at start
}
