# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "amd_pstate=guided" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-80ba2f13-f109-48d9-b023-76949435e6ef";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-80ba2f13-f109-48d9-b023-76949435e6ef".device = "/dev/disk/by-uuid/80ba2f13-f109-48d9-b023-76949435e6ef";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5032-D813";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7a298fe2-dc1b-4bbd-a84f-f7933acdb1fb"; }
    ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      rocmPackages.clr.icd
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true; # enable the bluetooth module
  hardware.bluetooth.powerOnBoot = false; # do not power up the bluetooth at start
}
