# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "amd_pstate=guided" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fca2066f-0439-4f0b-aa15-caee936022dc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fca2066f-0439-4f0b-aa15-caee936022dc".device = "/dev/disk/by-uuid/fca2066f-0439-4f0b-aa15-caee936022dc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E867-0185";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c582ce98-d5a2-4c33-9ff5-4d8e6f1e50d4"; }
    ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      rocmPackages.clr.icd
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true; # enable the bluetooth module
  hardware.bluetooth.powerOnBoot = false; # do not power up the bluetooth at start
}
